## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def func1(a,b):
    c=0
    try:
        c=a/b
        print(c)
    except ZeroDivisionError:
        print("Second value cannot be zero")
    except:
        print("try after some time")
    finally:
        print("thank you")
d=int(input("enter first number"))
e=int(input("enter second number"))
func1(d,e)
d=int(input("enter first number"))
e=int(input("enter second number"))
func1(d,e)
 

enter first number4
enter second number3
1.3333333333333333
thank you
enter first number5
enter second number0
Second value cannot be zero
thank you


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for a in subjects:
    for b in verbs:
        for c in objects:
            print(a+" "+b+" "+c)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [3]:
def VanderMonde(a,b):
    c=a.split(",")
    d=[]
    for i in c:  
        d.append(int(i))
    f=[]
    for i in d:
        e=[]
        for j in range(b-1,-1,-1):
            e.append(i**j)
        f.append(e)
    import numpy as np
    g=np.array(f)
    return g
a=input("enter the comma seperated number sequence")
b=int(input("enter number of columns in output matrix"))
print(VanderMonde(a,b))
a=input("enter the comma seperated number sequence")
b=int(input("enter number of columns in output matrix"))
VanderMonde(a,b)
        

enter the comma seperated number sequence1,2,3,4
enter number of columns in output matrix3
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
enter the comma seperated number sequence1,2,3,4
enter number of columns in output matrix5


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])