# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np
a=6*np.ones((5,5))
print('input matrix')
print(a)
a[1:-1,1:-1]=0
print('output matrix')
print(a)

input matrix
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
output matrix
[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
a=np.ones((8,8))*3
for i in range(4):
    for j in range(4):
        if(((2*i+1) in [1,3,5,7]) | ((2*j+1) in [1,3,5,7])):
            a[(2*i+1),(2*j+1)]=9
a


array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 9., 3., 9., 3., 9., 3., 9.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 9., 3., 9., 3., 9., 3., 9.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 9., 3., 9., 3., 9., 3., 9.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 9., 3., 9., 3., 9., 3., 9.]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
import numpy as np
print('empty array is:,',np.empty((3,3)))
a=np.ones((3,3))*6
a

empty array is:, [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.89715642e-321]
 [1.05699242e-307 8.01097888e-307 2.84327065e-308]]


array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
b=[0, 12, 45.21 ,34, 99.91]
a=np.array(b)
print('values in farenheit:')
print(b)
print('values in centigrade:')

print((a-32)*(5/9))

values in farenheit:
[0, 12, 45.21, 34, 99.91]
values in centigrade:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [5]:
a= [ 1.00000000+0.j, 0.70710678+0.70710678j]
b=np.array(a)
re=b.real
print('real parts is :',re)
im=b.imag
print('imaginary parts is:',im)

real parts is : [1.         0.70710678]
imaginary parts is: [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


array([10, 40])

Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [7]:
a=[0,10,20,40,60]
b=[10,30,40]
c=np.array(a)
d=np.array(b)
np.intersect1d(c,d)

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [8]:
print(np.unique([10,10,20,20,30,30]))
print(np.unique([[1 ,1],
[2, 3]]))

[10 20 30]
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [9]:
a=[ 0, 10, 20, 40, 60, 80]
b=[70,10, 30, 40, 50]
c=np.array(a)
d=np.array(b)
print('required solution is:')
np.setxor1d(c,d)

required solution is:


array([ 0, 20, 30, 50, 60, 70, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [12]:
a=[10, 20, 40, 60, 80]
c=np.array(a)
print(np.all(c))
b=[0,1,2,3]
np.all(b)

True


False

Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [16]:
a=[10, 20, 40, 60, 80]
c=np.array(a).reshape((5,1))
print(np.all(c,axis=1))
b=[0,1,2,3]
np.all(b,axis=0)

[ True  True  True  True  True]


False

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [11]:
a=[0, 10, 20, 40, 60, 80]
np.tile(a,2)

array([ 0, 10, 20, 40, 60, 80,  0, 10, 20, 40, 60, 80])

Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [10]:
a=[9,0, 10, 20, 40, 60, 80]
print('max element index in given list: ',np.where(a==np.amax(a)))
print('min element index in given list:',np.where(a==np.amin(a)))

max element index in given list:  (array([6], dtype=int64),)
min element index in given list: (array([1], dtype=int64),)


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [17]:
a=np.array([1,2])
b=np.array([4,5])
print('a>b:')
print(np.greater(a,b))
print('a>=b:')
print(np.greater_equal(a,b))
print('a<b')
print(np.less(a,b))
print('a<=b:')
print(np.less_equal(a,b))

a>b:
[False False]
a>=b:
[False False]
a<b
[ True  True]
a<=b:
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [18]:
a=[[2,5],[4,4]]
b=np.array(a)
print('original array:')
print(b)
print('sort along first axis')
c=np.sort(b,axis=0)
print(c)
print('sort along last axis')
np.sort(c,axis=1)

original array:
[[2 5]
 [4 4]]
sort along first axis
[[2 4]
 [4 5]]
sort along last axis


array([[2, 4],
       [4, 5]])

Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [19]:
first_names=( 'Margery','Betsey', 'Shelley', 'Lanell', 'Genesis' )
last_names=( 'Woolum','Battle', 'Plotner','Brien',  'Stahl' )
fi=np.array(first_names)
la=np.array(last_names)
np.lexsort((fi,la))

array([1, 3, 2, 4, 0], dtype=int64)

Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [20]:
a=[[ 0 ,10 ,20],
[20 ,30, 40]]
b=np.array(a)
b[b>10]

array([20, 20, 30, 40])

Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [21]:
a=np.ones((3,2))
print('size of the array is:')
a.size*(a.itemsize)

size of the array is:


48

## Great Job!